name: Publish Plugin Release
on:
  workflow_dispatch: {}
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish-maven-central:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Validate Gradle
        uses: gradle/actions/wrapper-validation@v4

      - name: Change Wrapper Permissions
        run: chmod +x ./gradlew

      - name: Publish Plugin Release
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publishToMavenCentral