name: Publish Plugin Release
on:
  workflow_dispatch: {}
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish-maven-central:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Validate Gradle
        uses: gradle/actions/wrapper-validation@v4

      - name: Change Wrapper Permissions
        run: chmod +x ./gradlew

      - name: Publish Plugin Release
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publish closeAndReleaseStagingRepositories